spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: pgadmin
    password: admin1234
  jpa:
    hibernate:
      default_schema: public
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      show_sql: true
      ddl-auto: update
      temp:
         use_jdbc_metadata_defaults: false


